---
title: "DS220 Wine Data"
author: "Joseph Sepich"
output: html_notebook
---

# Front matter

```{r echo = FALSE}
# always clean up R environment
rm(list = ls())

# load all packages here
library(mdsr) # book package of utilities
library(stringr) # utility package for strings
library(dplyr)
library(tidyr) # tidyverse utilities
library(lubridate) # date utility package
library(data.table)
```

```{r}
wines <- fread(file = "D:\\GitRepos\\DS220Proj2WineReview\\winemag-data-130k-v2.csv")
```

# Range of Wine Prices
```{r}
haveprice <- wines %>%
  filter(!is.na(price))
prices <- as.numeric(haveprice$price)
prices[which.max(prices)]
prices[which.min(prices)]
```

```{r}

library(data.table)
library(mdsr)

```
```{r}
wineInfo <- fread(file = "D:\\GitRepos\\DS220Proj2WineReview\\winemag-data-130k-v2.csv")
wineInfo <- wineInfo[1:10000,]
wineInfo[taster_name %in% c(""),10] <- "Unknown"

wines <- wineInfo %>%
  select(variety, price, winery, taster_name, title)
wines <- wines[!duplicated(wines[,c('variety', 'price')])]

wineries <- wineInfo %>%
  select(variety, winery, region_1, region_2, province, designation, country)
wineries <- wineries[!duplicated(wineries$winery)]

reviewers <- wineInfo %>%
  select(variety, winery, taster_name, taster_twitter_handle, title)
reviewers <- reviewers[!duplicated(reviewers$taster_name),]
```

# list of wines (15)
```{r}
write.csv(unqiue(wineInfo$variety), file = "D:\\GitRepos\\DS220Proj2WineReview\\wines.csv")
write.csv(unique(wineInfo$winery), file = "D:\\GitRepos\\DS220Proj2WineReview\\wineries.csv")
write.csv(unique(wineInfo$region_1), file = "D:\\GitRepos\\DS220Proj2WineReview\\regions.csv")
write.csv(unique(wineInfo$country), file = "D:\\GitRepos\\DS220Proj2WineReview\\countries.csv")
```



